# Render Blueprint Configuration
# Deploy Google Maps Crawler với PostgreSQL database

databases:
  - name: ggmaps-db
    plan: starter
    databaseName: ggmaps
    user: ggmaps

services:
  - type: web
    name: google-maps-crawler
    runtime: python
    plan: starter
    repo: https://github.com/tuanhqv123/data_review_ggmaps.git
    buildCommand: pip install --upgrade pip setuptools wheel && pip install --only-binary=:all: greenlet==3.0.1 && pip install -r requirements.txt && playwright install chromium
    startCommand: python main.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ggmaps-db
          property: connectionString
      - key: DB_HOST
        fromDatabase:
          name: ggmaps-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: ggmaps-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: ggmaps-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: ggmaps-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ggmaps-db
          property: password
      - key: PYTHONUNBUFFERED
        value: "1"
